name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ts"

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.29.1"
      - name: Run core tests
        run: |
          deno test \
          $(ls core/**/*_test.ts)
      - name: Run utilities tests
        run: |
          deno test \
          $(ls utils/**/*_test.ts)
      - name: Run writer tests
        run: |
          deno test \
            --allow-write \
            --allow-read \
            $(ls writer/**/*_test.ts)
