name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - constants/**
      - core/**
      - types/**
      - utils/**

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.29.1"
      - name: Run tests
        run: |
          deno test